// 商品类别与目标市场选项：为搜索下拉框提供可复用的业务词典。
export type CatalogOption = {
  value: string
  group: string
  keywords?: string
}

export const productCategoryOptions: CatalogOption[] = [
  { value: '犬用胸背带', group: '宠物用品', keywords: '狗 胸背 牵引 harness' },
  { value: '宠物项圈与牵引用品', group: '宠物用品', keywords: '狗绳 猫 项圈 leash collar' },
  { value: '宠物喂食器与饮水机', group: '宠物用品', keywords: '宠物碗 猫咪饮水机 feeder fountain' },
  { value: '宠物床垫与窝具', group: '宠物用品', keywords: '狗窝 猫窝 pet bed' },
  { value: '宠物清洁与美容用品', group: '宠物用品', keywords: '洗护 梳毛 指甲 grooming' },
  { value: '宠物玩具', group: '宠物用品', keywords: '猫玩具 狗玩具 pet toy' },
  { value: '猫砂与猫砂盆', group: '宠物用品', keywords: 'litter box' },
  { value: '宠物服饰', group: '宠物用品', keywords: '狗衣服 猫衣服 pet apparel' },
  { value: '宠物出行用品', group: '宠物用品', keywords: '航空箱 推车 carrier stroller' },
  { value: '水族与小宠用品', group: '宠物用品', keywords: '鱼缸 仓鼠 aquarium' },
  { value: '厨房工具与小器具', group: '家居生活', keywords: '厨具 kitchen gadget' },
  { value: '餐具与饮具', group: '家居生活', keywords: '杯子 保温杯 餐盘 drinkware' },
  { value: '烘焙用品', group: '家居生活', keywords: '模具 baking' },
  { value: '家居收纳', group: '家居生活', keywords: '整理盒 organizer storage' },
  { value: '家居清洁用品', group: '家居生活', keywords: '清洁刷 拖把 cleaning' },
  { value: '家纺与床上用品', group: '家居生活', keywords: '床单 毯子 textile bedding' },
  { value: '浴室用品', group: '家居生活', keywords: '卫浴 bathroom' },
  { value: '家具与家居装饰', group: '家居生活', keywords: '摆件 furniture decor' },
  { value: '灯具与照明', group: '家居生活', keywords: '台灯 LED lighting' },
  { value: '园艺与庭院用品', group: '家居生活', keywords: '花盆 garden patio' },
  { value: '手机与平板配件', group: '消费电子', keywords: '手机壳 充电器 mobile tablet accessories' },
  { value: '电脑与办公设备', group: '消费电子', keywords: '键盘 鼠标 显示器 computer office' },
  { value: '耳机与音频设备', group: '消费电子', keywords: '蓝牙耳机 音箱 audio headphone' },
  { value: '智能穿戴设备', group: '消费电子', keywords: '手环 智能手表 wearable' },
  { value: '摄影与视频配件', group: '消费电子', keywords: '相机 支架 camera video' },
  { value: '智能家居设备', group: '消费电子', keywords: '传感器 开关 smart home' },
  { value: '游戏设备与配件', group: '消费电子', keywords: '手柄 gaming' },
  { value: '电子元器件与配件', group: '消费电子', keywords: 'electronics component' },
  { value: '女装', group: '服饰鞋包', keywords: 'women apparel clothing' },
  { value: '男装', group: '服饰鞋包', keywords: 'men apparel clothing' },
  { value: '童装', group: '服饰鞋包', keywords: 'kids clothing' },
  { value: '内衣与家居服', group: '服饰鞋包', keywords: 'underwear sleepwear' },
  { value: '鞋靴', group: '服饰鞋包', keywords: 'shoes boots' },
  { value: '箱包与旅行用品', group: '服饰鞋包', keywords: '行李箱 背包 luggage bag' },
  { value: '珠宝首饰', group: '服饰鞋包', keywords: 'jewelry' },
  { value: '手表与配饰', group: '服饰鞋包', keywords: 'watch accessory' },
  { value: '护肤品', group: '美妆健康', keywords: 'skincare' },
  { value: '彩妆与美妆工具', group: '美妆健康', keywords: 'makeup cosmetics' },
  { value: '美发护发用品', group: '美妆健康', keywords: 'hair care' },
  { value: '个人护理用品', group: '美妆健康', keywords: 'personal care' },
  { value: '香水与香氛', group: '美妆健康', keywords: 'perfume fragrance' },
  { value: '健康护理用品', group: '美妆健康', keywords: 'health care' },
  { value: '健身器材与配件', group: '运动户外', keywords: 'fitness gym' },
  { value: '露营与徒步用品', group: '运动户外', keywords: 'camping hiking' },
  { value: '骑行用品', group: '运动户外', keywords: '自行车 cycling' },
  { value: '球类与团队运动用品', group: '运动户外', keywords: 'ball team sports' },
  { value: '水上与冬季运动用品', group: '运动户外', keywords: '游泳 滑雪 water winter sports' },
  { value: '母婴用品', group: '母婴玩具', keywords: 'baby maternity' },
  { value: '玩具与游戏', group: '母婴玩具', keywords: 'toy game' },
  { value: '教育与益智用品', group: '母婴玩具', keywords: 'education learning' },
  { value: '文具与办公用品', group: '办公文教', keywords: 'stationery office supplies' },
  { value: '艺术与手工用品', group: '办公文教', keywords: 'craft art' },
  { value: '图书与印刷品', group: '办公文教', keywords: 'book print' },
  { value: '汽车用品与配件', group: '汽车工具', keywords: 'automotive car' },
  { value: '摩托车用品与配件', group: '汽车工具', keywords: 'motorcycle' },
  { value: '五金工具', group: '汽车工具', keywords: 'hardware tools' },
  { value: '家装与维修用品', group: '汽车工具', keywords: 'home improvement DIY' },
  { value: '食品与饮料', group: '其他常用品类', keywords: 'food beverage' },
  { value: '派对与节庆用品', group: '其他常用品类', keywords: 'party seasonal' },
  { value: '工业与商业用品', group: '其他常用品类', keywords: 'industrial business B2B' },
]

export const targetMarketOptions: CatalogOption[] = [
  { value: '美国跨境电商市场', group: '北美', keywords: '美国 美利坚 USA United States US' },
  { value: '加拿大跨境电商市场', group: '北美', keywords: '加拿大 Canada CA' },
  { value: '墨西哥跨境电商市场', group: '北美', keywords: '墨西哥 Mexico MX' },
  { value: '英国跨境电商市场', group: '欧洲', keywords: '英国 United Kingdom UK GB' },
  { value: '德国跨境电商市场', group: '欧洲', keywords: '德国 Germany DE' },
  { value: '法国跨境电商市场', group: '欧洲', keywords: '法国 France FR' },
  { value: '意大利跨境电商市场', group: '欧洲', keywords: '意大利 Italy IT' },
  { value: '西班牙跨境电商市场', group: '欧洲', keywords: '西班牙 Spain ES' },
  { value: '荷兰跨境电商市场', group: '欧洲', keywords: '荷兰 Netherlands NL' },
  { value: '比利时跨境电商市场', group: '欧洲', keywords: '比利时 Belgium BE' },
  { value: '波兰跨境电商市场', group: '欧洲', keywords: '波兰 Poland PL' },
  { value: '瑞典跨境电商市场', group: '欧洲', keywords: '瑞典 Sweden SE' },
  { value: '欧洲联盟多国市场', group: '欧洲', keywords: '欧盟 欧洲 EU Europe' },
  { value: '日本跨境电商市场', group: '东亚', keywords: '日本 Japan JP' },
  { value: '韩国跨境电商市场', group: '东亚', keywords: '韩国 South Korea KR' },
  { value: '中国香港跨境电商市场', group: '东亚', keywords: '香港 Hong Kong HK' },
  { value: '中国台湾跨境电商市场', group: '东亚', keywords: '台湾 Taiwan TW' },
  { value: '新加坡跨境电商市场', group: '东南亚', keywords: '新加坡 Singapore SG' },
  { value: '马来西亚跨境电商市场', group: '东南亚', keywords: '马来西亚 Malaysia MY' },
  { value: '泰国跨境电商市场', group: '东南亚', keywords: '泰国 Thailand TH' },
  { value: '越南跨境电商市场', group: '东南亚', keywords: '越南 Vietnam VN' },
  { value: '菲律宾跨境电商市场', group: '东南亚', keywords: '菲律宾 Philippines PH' },
  { value: '印度尼西亚跨境电商市场', group: '东南亚', keywords: '印尼 Indonesia ID' },
  { value: '东南亚多国市场', group: '东南亚', keywords: 'ASEAN Southeast Asia' },
  { value: '印度跨境电商市场', group: '南亚', keywords: '印度 India IN' },
  { value: '澳大利亚跨境电商市场', group: '大洋洲', keywords: '澳洲 Australia AU' },
  { value: '新西兰跨境电商市场', group: '大洋洲', keywords: '新西兰 New Zealand NZ' },
  { value: '阿联酋跨境电商市场', group: '中东', keywords: '迪拜 阿联酋 UAE United Arab Emirates AE' },
  { value: '沙特阿拉伯跨境电商市场', group: '中东', keywords: '沙特 Saudi Arabia SA' },
  { value: '以色列跨境电商市场', group: '中东', keywords: '以色列 Israel IL' },
  { value: '中东多国市场', group: '中东', keywords: 'Middle East GCC 海湾' },
  { value: '巴西跨境电商市场', group: '拉丁美洲', keywords: '巴西 Brazil BR' },
  { value: '智利跨境电商市场', group: '拉丁美洲', keywords: '智利 Chile CL' },
  { value: '哥伦比亚跨境电商市场', group: '拉丁美洲', keywords: '哥伦比亚 Colombia CO' },
  { value: '拉丁美洲多国市场', group: '拉丁美洲', keywords: 'Latin America LATAM' },
  { value: '南非跨境电商市场', group: '非洲', keywords: '南非 South Africa ZA' },
  { value: '尼日利亚跨境电商市场', group: '非洲', keywords: '尼日利亚 Nigeria NG' },
]
